spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/ayil_bank}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
  
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

logging:
  level:
    kg.ayil_bank: INFO
    org.springframework.transaction: WARN
    org.hibernate.SQL: WARN
  file:
    name: /var/log/ayil_bank/application.log
