spring:
  application:
    name: ayil_bank
  
  profiles:
    active: local
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    kg.ayil_bank: INFO
